In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
arr = np.array([[1,2] ,[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [7]:
arr = np.zeros((2,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]]


In [8]:
arr = np.ones((2,3) , dtype=float)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr = np.full((3,4) , 5)
print(arr) 

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [11]:
arr = np.arange(10,20,5)
print(arr)

[10 15]


In [13]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
arr = np.random.random((3,3))
print(arr)

[[0.32960796 0.1698689  0.2126913 ]
 [0.2592074  0.71134471 0.60961684]
 [0.49027372 0.52786062 0.52955933]]


In [16]:
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(3, 3)
9
2
float64


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0,1])
print(arr[1:3 , 0:2])


2
[[4 5]
 [7 8]]


In [21]:
print(arr[arr>5])

[6 7 8 9]


In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(arr1*2)
print(np.sum(arr1))
print(arr2.mean())
print(arr1.max())


[5 7 9]
[2 4 6]
6
5.0
3


In [29]:
arr = np.array([[1,2,3] , [4,5,6]])
print(arr.sum(axis = 0))
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [30]:
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [32]:
print(arr.ravel())
print(arr.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [38]:
print(np.split(arr,2,axis = 0))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [42]:
A = np.array([[1,2] , [3,4]])
B = np.array([[5,6] , [6,7]])
print(np.dot(A,B))
print(np.linalg.det(A))
print(np.linalg.inv(A))

[[17 20]
 [39 46]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [47]:
arr = np.array([3,1,4,1,5])
print(np.sort(arr))
print(np.argsort(arr))
print(np.unique(arr))

[1 1 3 4 5]
[1 3 0 2 4]
[1 3 4 5]


In [48]:
arr = np.array([1,-2,3,-4])
print(np.where(arr>0 , arr ,0))

[1 0 3 0]
